In [1]:
import numpy as np
# 1. Create a rank 2(2D) array
arr = np.array([[11,12,13,14],[15,16,17,18]])

print(arr)

# 2. Create an array with 4 rows and 3 columns of zeros
A = np.zeros((4,3))

print(A)

#3. Create an array of ones that has 3 rows and 4 columns

B = np.ones((3,4))

print(B)

#4.  Create an array containing integers 4 to 13 inclusive. Your results should look as below:

range1 = np.arange(4,14)
print(range1)

#5. Create an array containing [0., 1.5, 3., 4.5]

range2 = np.linspace(0,4.5,4)

print(range2)

#Create a 2 by 2 array containing '4' in each position. Your results should look like this: [[4 4],[4 4]]
range3 = np.full((2,2),4)
print(range3)

#Create 2 matrices:
#Identity matrix of size 4
range4 = np.eye(4)
print(range4)

#Diagonal matrix with [10,12] as the diagonals

range5 = np.diag([10,12])
print(range5)

#Create a 3 by 3 array with random floats in [0, 10]
range6 = np.random.random((3,3)*10)
print(range6)



[[11 12 13 14]
 [15 16 17 18]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 4  5  6  7  8  9 10 11 12 13]
[0.  1.5 3.  4.5]
[[4 4]
 [4 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0]
 [ 0 12]]


MemoryError: Unable to allocate 26.0 GiB for an array with shape (3486784401,) and data type float64

In [2]:
import numpy    as np
#ADDING ELEMENTS
#Use this array for the following practice:

myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])

#1. Add a new row of elements containing 20, 21 and 22

new_row = np.array([20,21,22])
updated_array = np.vstack((myArray,new_row))
print(updated_array)

#2. Add a new column of elements containing 30, 40 and 50
new_column = np.array([[30],[40],[50]])

updated_column_array = np.hstack((myArray,new_column))
print(updated_column_array)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]]


In [3]:
import numpy as np
#Remove the elements from the middle column of this array:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
myArray_new = np.delete(myArray,1,axis=1)
print(myArray_new)

[[1 3]
 [4 6]
 [9 7]]


In [4]:
import numpy as np

#INSERTING ELEMENTS
myArray = np.zeros((2,2))
print(myArray, "\n")


#Add 1 column of 1 to this array:

myArray_1 = np.append(myArray,np.ones((2,1)),axis=1)
print(myArray_1, "\n")

#Add 2 rows of 2 to the answer from part 1
myArray_2 = np.append(myArray_1,[[2,2,2],[2,2,2]],axis=0)
print(myArray_2, "\n")

#Remove the last column
myArray_3 = np.delete(myArray_2,2,axis=1)
print(myArray_3, "\n")
#Remove the last row
myArray_4 = np.delete(myArray_3,3,axis=0)
print(myArray_4, "\n")

[[0. 0.]
 [0. 0.]] 

[[0. 0. 1.]
 [0. 0. 1.]] 

[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]
 [2. 2. 2.]] 

[[0. 0.]
 [0. 0.]
 [2. 2.]
 [2. 2.]] 

[[0. 0.]
 [0. 0.]
 [2. 2.]] 


In [5]:
import numpy as np
#Use this array for the following practice:

myArray = np.arange(10)

#1. Find the square of every number in array

squared_array = myArray **2
print(squared_array)

#2. Find the square root of every number in array
squaredroot_array = np.sqrt(myArray)
print(squaredroot_array)

#3. Multiply the square of each number in array with its respective square root
multiply_array = squared_array * squaredroot_array
print(multiply_array)

[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


In [6]:
import numpy as np

# Slice

myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
#a. Get a subarray of the first row and first 2 columns. Your results should look like this:
#[11 12]

print(myArray[0,0:2])

#b. Change all elements in 1st and second row to 0. Your results should look like this:
myArray[0:2] = 0
print(myArray)

#2. Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.

myArr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
reversed_myArr = myArr[::-1]
print(reversed_myArr)

#Use this array for the following practice:
mynewArray = np.array([[11,12,13], [14,15,16]])

#Reshape the array to an array with 3 rows. Your results should look like this:
#[11 12]
#[13 14]
#[15 16]]

reshaped_array = mynewArray.reshape(3,2)
print(reshaped_array)

[11 12]
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[[11 12]
 [13 14]
 [15 16]]


In [7]:
import numpy as np
#Replace all odd numbers in the given array with -1
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 == 1] = -1
print(exercise_1)


#Convert a 1-D array into a 2-D array with 3 rows
exercise_2 = np.array([0,1,2,3,4,5,6,7,8])
## Convert exercise_2 into a 2-D array with 3 rows
exercise_2_reshaped = exercise_2.reshape(3, -1)
print(exercise_2_reshaped)

#Add 202 to all the values in given array

exercise_3 = np.arange(4).reshape(2,-1)
# Add 202 to all the values in exercise_3
exercise_3_updated = exercise_3 + 202
print(exercise_3_updated)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[202 203]
 [204 205]]
